init:
    define augustus_song = "audio/Augustus low pass.wav"
    define augustus_chomp = "audio/chomp augustus.wav"
    define veruca_crack = "audio/teeth crack.wav"
    define veruca_scream ="audio/girl scream.wav"
    define nuclear_alarm ="audio/nuclear alarm.wav"
    define violet_scream ="audio/girl scream 2.wav"
    define ballon_pop ="audio/ballon pop.wav"
    define bang_w ="audio/bang wonka.wav"
    define bang_w_2 ="audio/bang wonka 2.wav"
    define classic = "audio/winter vivaldi.wav"
    define aSplash = "audio/splash.wav"
    define napoleon = "audio/napoleon song.wav"